# Generated by Django 6.0 on 2025-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=2000, null=True)),
                ('imagen', models.CharField(max_length=2000, null=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
